import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Метадата: браузер, Apple құрылғылары және іздеу үшін
export const metadata: Metadata = {
  title: "A-PRO Limited",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon-32x32.png',  // негізгі иконка
    apple: '/favicon-32x32.png', // Apple құрылғылары үшін
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon барлық жерде көріну үшін қосымша тегтер */}
        <link rel="icon" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="apple-touch-icon" href="/favicon-32x32.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col min-h-screen'>
          {children}
        </div>
      </body>
    </html>
  );
}
